# Canonical build, validation, documentation, and release-artifact entry points.

SHELL := /bin/sh
.SHELLFLAGS := -eu -c

DIST_DIR := dist
SOURCE_FILTER := doxygen-bash.awk
DIST_FILTER := $(DIST_DIR)/doxygen-bash.awk
DIST_CHECKSUM := $(DIST_FILTER).sha256
AWK_BIN ?= awk

VENDOR_DIR := vendor
DOCS_MANIFEST := dependencies-docs.txt
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.0.10
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := acbe79d39ab8cbbf906bd864d410ba7a223ba6f09501c02a409b8d3aa8740462
VENDOR_AWK_FILTER := $(VENDOR_DIR)/doxygen-awk.awk
VENDOR_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
REFERENCE_DOC_DIR := doc/reference
AWK_DOXYGEN_FILTER ?= $(VENDOR_AWK_FILTER)
BASH_DOXYGEN_FILTER ?= $(VENDOR_BASH_FILTER)

VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build checksums clean deps-docs deps-docs-check distclean docs docs-canary docs-clean test test-source test-dist verify-bashdeps FORCE

all: build

## Build the exact consumer artifact with immutable provenance metadata.
##
## The build target is intentionally phony because VERSION, BUILD_DATE, and
## BUILD_COMMIT are build inputs rather than filesystem prerequisites. Rebuilding
## prevents development metadata from leaking into a later release artifact.
## The maintained awk source remains the source of truth; the generated artifact
## preserves its executable shebang and adds metadata only as comments so the
## filter's runtime behavior and awk namespace remain unchanged.
build: $(SOURCE_FILTER)
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/awk -f'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Source files: $(SOURCE_FILTER)'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# DOXYGEN_BASH_VERSION=$(VERSION)'; \
		printf '%s\n' '# DOXYGEN_BASH_BUILD_DATE=$(BUILD_DATE)'; \
		printf '%s\n' '# DOXYGEN_BASH_BUILD_COMMIT=$(BUILD_COMMIT)'; \
		printf '%s\n' '#'; \
		tail -n +2 "$(SOURCE_FILTER)"; \
	} >"$(DIST_FILTER).tmp"
	chmod 0755 "$(DIST_FILTER).tmp"
	mv "$(DIST_FILTER).tmp" "$(DIST_FILTER)"

## Run the regression suite against both maintained source and consumer output.
test: test-source test-dist

## Run the regression suite against the maintained source file.
test-source:
	DOXYGEN_BASH_FILTER="$(SOURCE_FILTER)" sh ./tests/run-tests.sh

## Build and run the regression suite against the exact consumer artifact.
##
## Verify the generated-file boundary itself before exercising filter behavior.
test-dist: build
	test "$$(head -n 1 "$(DIST_FILTER)")" = '#!/usr/bin/awk -f'
	grep -Fxq '# Generated by make build. Do not edit directly.' "$(DIST_FILTER)"
	grep -Fxq '# Source files: $(SOURCE_FILTER)' "$(DIST_FILTER)"
	grep -Fxq '# DOXYGEN_BASH_VERSION=$(VERSION)' "$(DIST_FILTER)"
	grep -Fxq '# DOXYGEN_BASH_BUILD_DATE=$(BUILD_DATE)' "$(DIST_FILTER)"
	grep -Fxq '# DOXYGEN_BASH_BUILD_COMMIT=$(BUILD_COMMIT)' "$(DIST_FILTER)"
	DOXYGEN_BASH_FILTER="$(DIST_FILTER)" sh ./tests/run-tests.sh

## Generate the SHA-256 checksum for the exact consumer artifact.
##
## The checksum is generated from inside dist so users can download both files
## into one directory and verify them with sha256sum -c doxygen-bash.awk.sha256.
checksums: build
	cd "$(DIST_DIR)" && sha256sum "$(notdir $(DIST_FILTER))" >"$(notdir $(DIST_CHECKSUM))"

FORCE:

## Bootstrap only bashdeps directly, verifying pinned bytes before execution.
$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { \
		path=$$1; \
		if command -v sha256sum >/dev/null 2>&1; then \
			printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; \
		elif command -v shasum >/dev/null 2>&1; then \
			[ "$$(shasum -a 256 "$$path" | awk '{print $$1}')" = "$(BASHDEPS_SHA256)" ]; \
		else \
			return 2; \
		fi; \
	}; \
	if [ -f "$@" ] && verify_hash "$@"; then chmod 0755 "$@"; exit 0; fi; \
	tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; \
	if command -v curl >/dev/null 2>&1; then \
		curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; \
	elif command -v wget >/dev/null 2>&1; then \
		wget -qO "$$tmp" "$(BASHDEPS_URL)"; \
	else \
		printf '%s\n' 'curl or wget is required to bootstrap bashdeps.bash' >&2; exit 1; \
	fi; \
	verify_hash "$$tmp" || { printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; exit 1; }; \
	chmod 0755 "$$tmp"; mv "$$tmp" "$@"; trap - EXIT

## Verify the pinned bashdeps bootstrap without network access or repair.
verify-bashdeps:
	@test -x "$(BASHDEPS)" || { printf '%s\n' 'Missing or non-executable vendor/bashdeps.bash; run make deps-docs' >&2; exit 1; }
	@if command -v sha256sum >/dev/null 2>&1; then \
		printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null 2>&1 || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps-docs' >&2; exit 1; }; \
	elif command -v shasum >/dev/null 2>&1; then \
		[ "$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')" = "$(BASHDEPS_SHA256)" ] || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps-docs' >&2; exit 1; }; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; exit 1; \
	fi

## Synchronize documentation-only dependencies; this target may use the network.
deps-docs: $(BASHDEPS) $(DOCS_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DOCS_MANIFEST)"

## Verify prepared documentation dependencies without network access or repair.
deps-docs-check: verify-bashdeps $(DOCS_MANIFEST)
	"$(BASHDEPS)" verify "$(DOCS_MANIFEST)"

## Generate stable reference documentation with bashdeps-pinned released filters.
docs: deps-docs-check
	$(MAKE) --no-print-directory docs-canary \
		AWK_DOXYGEN_FILTER="$(VENDOR_AWK_FILTER)" \
		BASH_DOXYGEN_FILTER="$(VENDOR_BASH_FILTER)"

## Generate reference documentation with explicitly selected filter paths.
##
## This target is also the common integration-canary path.  It does not acquire
## or repair dependencies; callers prepare stable filter dependencies separately
## and may substitute current-source or exact-release Bash filter bytes.
docs-canary:
	@test -f "$(AWK_DOXYGEN_FILTER)" || { printf '%s\n' 'Missing AWK Doxygen filter' >&2; exit 1; }
	@test -f "$(BASH_DOXYGEN_FILTER)" || { printf '%s\n' 'Missing Bash Doxygen filter' >&2; exit 1; }
	chmod 0755 "$(AWK_DOXYGEN_FILTER)" "$(BASH_DOXYGEN_FILTER)"
	"$(AWK_BIN)" -f "$(AWK_DOXYGEN_FILTER)" -- --strict --compact "$(SOURCE_FILTER)" >/dev/null
	awk -f "$(BASH_DOXYGEN_FILTER)" -- --strict --compact ./tests/run-tests.sh >/dev/null
	$(MAKE) --no-print-directory docs-clean
	AWK_DOXYGEN_FILTER="$(abspath $(AWK_DOXYGEN_FILTER))" \
	BASH_DOXYGEN_FILTER="$(abspath $(BASH_DOXYGEN_FILTER))" \
		doxygen Doxyfile

## Remove generated reference documentation.
docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"

clean: docs-clean
	rm -rf "$(DIST_DIR)"

## Remove all generated build, reference, and dependency state.
distclean: clean
	rm -rf "$(VENDOR_DIR)"

include mk/megalinter.mk
