# Canonical build, validation, documentation, and release-artifact entry points.

SHELL := /bin/sh
.SHELLFLAGS := -eu -c

DIST_DIR := dist
SOURCE_FILTER := doxygen-bash.awk
AWK_SOURCES := $(SOURCE_FILTER)
DIST_DEV_FILTER := $(DIST_DIR)/doxygen-bash.dev.awk
DIST_FILTER := $(DIST_DIR)/doxygen-bash.awk
DIST_MIN_FILTER := $(DIST_DIR)/doxygen-bash.min.awk
DIST_FILTERS := $(DIST_DEV_FILTER) $(DIST_FILTER) $(DIST_MIN_FILTER)
DIST_CHECKSUMS := $(addsuffix .sha256,$(DIST_FILTERS))
AWK_BIN ?= awk

VENDOR_DIR := vendor
DEPENDENCY_MANIFEST := dependencies.txt
DOCS_MANIFEST := dependencies-docs.txt
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.0.10
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := acbe79d39ab8cbbf906bd864d410ba7a223ba6f09501c02a409b8d3aa8740462
AWK_MINIFIER := $(VENDOR_DIR)/awk-minifier.awk
AWK_MINIFIER_VERSION := 0.2.4
VENDOR_AWK_FILTER := $(VENDOR_DIR)/doxygen-awk.awk
VENDOR_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
ADRCTL := $(VENDOR_DIR)/adrctl.bash
ADR_DIR := doc/adr
ADR_INDEX_FILE := $(ADR_DIR)/README.md
ADR_INDEX_INTRO := $(ADR_DIR)/README.intro.md
ADR_INDEX_OUTRO := $(ADR_DIR)/README.outro.md
REFERENCE_DOC_DIR := doc/reference
AWK_DOXYGEN_FILTER ?= $(VENDOR_AWK_FILTER)
BASH_DOXYGEN_FILTER ?= $(VENDOR_BASH_FILTER)

VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: adr-index all build check checksums clean deps deps-check deps-docs deps-docs-check distclean docs docs-canary docs-clean test test-source test-dist verify-bashdeps verify-build-deps FORCE

all: build

## Build the development, ordinary, and minified consumer artifacts and checksums.
##
## Build is intentionally offline. Repository tooling must already have been
## prepared with make deps and is verified before any generated artifact is
## published. VERSION, BUILD_DATE, and BUILD_COMMIT are build inputs rather than
## filesystem prerequisites, so the development artifact is forced to rebuild.
build: verify-build-deps
	$(MAKE) --no-print-directory $(DIST_FILTERS) $(DIST_CHECKSUMS)

## Build the full development artifact with immutable provenance metadata.
$(DIST_DEV_FILTER): FORCE $(SOURCE_FILTER)
	@mkdir -p "$(DIST_DIR)"
	@{ \
		printf '%s\n' '#!/usr/bin/awk -f'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Artifact: development'; \
		printf '%s\n' '# Source files: $(SOURCE_FILTER)'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# DOXYGEN_BASH_VERSION=$(VERSION)'; \
		printf '%s\n' '# DOXYGEN_BASH_BUILD_DATE=$(BUILD_DATE)'; \
		printf '%s\n' '# DOXYGEN_BASH_BUILD_COMMIT=$(BUILD_COMMIT)'; \
		printf '%s\n' '# End generated header.'; \
		printf '\n'; \
		tail -n +2 "$(SOURCE_FILTER)"; \
	} >"$@.tmp"
	@chmod 0755 "$@.tmp"
	@mv "$@.tmp" "$@"

## Build the ordinary artifact by removing full-line comments from source body.
##
## The generated provenance header is build-owned metadata and remains intact.
$(DIST_FILTER): $(DIST_DEV_FILTER)
	@sed \
		-e '1,/^# End generated header\.$$/!{/^[[:space:]]*#/d;}' \
		-e 's/^# Artifact: development$$/# Artifact: ordinary/' \
		"$<" >"$@.tmp"
	@chmod 0755 "$@.tmp"
	@mv "$@.tmp" "$@"

## Build the minified artifact with the pinned AWK Minifier release.
##
## The build-owned provenance header stays outside the transformer input so the
## artifact remains self-identifying after source comments and whitespace are
## removed from its body.
$(DIST_MIN_FILTER): $(DIST_FILTER) $(AWK_MINIFIER)
	@body="$@.body.tmp"; \
	trap 'rm -f "$$body" "$@.tmp"' EXIT; \
	sed '1,/^# End generated header\.$$/d' "$<" | \
		"$(AWK_BIN)" -f "$(AWK_MINIFIER)" >"$$body"; \
	{ \
		printf '%s\n' '#!/usr/bin/awk -f'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Artifact: minified'; \
		printf '%s\n' '# Source files: $(SOURCE_FILTER)'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# DOXYGEN_BASH_VERSION=$(VERSION)'; \
		printf '%s\n' '# DOXYGEN_BASH_BUILD_DATE=$(BUILD_DATE)'; \
		printf '%s\n' '# DOXYGEN_BASH_BUILD_COMMIT=$(BUILD_COMMIT)'; \
		printf '%s\n' '# Minifier: AWK Minifier v$(AWK_MINIFIER_VERSION)'; \
		printf '%s\n' '# Minifier input: doxygen-bash.awk ordinary artifact body'; \
		printf '%s\n' '# End generated header.'; \
		cat "$$body"; \
	} >"$@.tmp"; \
	chmod 0755 "$@.tmp"; \
	mv "$@.tmp" "$@"; \
	rm -f "$$body"; \
	trap - EXIT

## Generate a SHA-256 checksum beside each executable distribution artifact.
$(DIST_DIR)/%.awk.sha256: $(DIST_DIR)/%.awk
	@digest=''; \
	if command -v sha256sum >/dev/null 2>&1; then \
		digest="$$(sha256sum "$<" | awk '{print $$1}')"; \
	elif command -v shasum >/dev/null 2>&1; then \
		digest="$$(shasum -a 256 "$<" | awk '{print $$1}')"; \
	else \
		printf '%s\n' 'No SHA-256 command is available for build checksums' >&2; \
		exit 1; \
	fi; \
	printf '%s  %s\n' "$$digest" "$(notdir $<)" >"$@.tmp"; \
	mv "$@.tmp" "$@"

checksums: build

## Run GNU awk lint against maintained root AWK sources.
check:
	@command -v gawk >/dev/null 2>&1 || { printf '%s\n' 'gawk is required for make check' >&2; exit 1; }
	@for source in $(AWK_SOURCES); do \
		printf '%s\n' "Linting $$source"; \
		gawk --lint=fatal -v strict=0 -v compact=0 -f "$$source" </dev/null >/dev/null; \
	done

## Run one TAP stream against maintained source and all distribution artifacts.
test: build
	@AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh \
		source="$(SOURCE_FILTER)" \
		development="$(DIST_DEV_FILTER)" \
		ordinary="$(DIST_FILTER)" \
		minified="$(DIST_MIN_FILTER)"

## Run the TAP regression suite against maintained source only.
test-source:
	@AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh source="$(SOURCE_FILTER)"

## Build and run one TAP stream against all exact distribution artifacts.
test-dist: build
	@AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh \
		development="$(DIST_DEV_FILTER)" \
		ordinary="$(DIST_FILTER)" \
		minified="$(DIST_MIN_FILTER)"

FORCE:

## Bootstrap only bashdeps directly, verifying pinned bytes before execution.
$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { \
		path=$$1; \
		if command -v sha256sum >/dev/null 2>&1; then \
			printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; \
		elif command -v shasum >/dev/null 2>&1; then \
			[ "$$(shasum -a 256 "$$path" | awk '{print $$1}')" = "$(BASHDEPS_SHA256)" ]; \
		else \
			return 2; \
		fi; \
	}; \
	if [ -f "$@" ] && verify_hash "$@"; then chmod 0755 "$@"; exit 0; fi; \
	tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; \
	if command -v curl >/dev/null 2>&1; then \
		curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; \
	elif command -v wget >/dev/null 2>&1; then \
		wget -qO "$$tmp" "$(BASHDEPS_URL)"; \
	else \
		printf '%s\n' 'curl or wget is required to bootstrap bashdeps.bash' >&2; exit 1; \
	fi; \
	verify_hash "$$tmp" || { printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; exit 1; }; \
	chmod 0755 "$$tmp"; mv "$$tmp" "$@"; trap - EXIT

## Verify the pinned bashdeps bootstrap without network access or repair.
verify-bashdeps:
	@test -x "$(BASHDEPS)" || { printf '%s\n' 'Missing or non-executable vendor/bashdeps.bash; run make deps or make deps-docs' >&2; exit 1; }
	@if command -v sha256sum >/dev/null 2>&1; then \
		printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null 2>&1 || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps or make deps-docs' >&2; exit 1; }; \
	elif command -v shasum >/dev/null 2>&1; then \
		[ "$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')" = "$(BASHDEPS_SHA256)" ] || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps or make deps-docs' >&2; exit 1; }; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; exit 1; \
	fi

## Synchronize ordinary build dependencies; this target may use the network.
deps: $(BASHDEPS) $(DEPENDENCY_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DEPENDENCY_MANIFEST)"

## Verify prepared build dependencies without network access or repair.
deps-check: verify-build-deps

verify-build-deps: verify-bashdeps $(DEPENDENCY_MANIFEST)
	"$(BASHDEPS)" verify "$(DEPENDENCY_MANIFEST)"

## Synchronize documentation-only dependencies; this target may use the network.
deps-docs: $(BASHDEPS) $(DOCS_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DOCS_MANIFEST)"

## Verify prepared documentation dependencies without network access or repair.
deps-docs-check: verify-bashdeps $(DOCS_MANIFEST)
	"$(BASHDEPS)" verify "$(DOCS_MANIFEST)"

## Generate the ephemeral ADR landing page from maintained framing and ADR source.
##
## This target consumes prepared released-adrctl state and never synchronizes or
## repairs documentation dependencies. A same-directory candidate replaces the
## published intermediate only after successful generation.
adr-index:
	@test -r "$(ADRCTL)" || { printf '%s\n' 'Missing documentation dependency vendor/adrctl.bash; run make deps-docs first' >&2; exit 1; }
	@test -r "$(ADR_INDEX_INTRO)" || { printf '%s\n' 'Missing ADR landing-page introduction' >&2; exit 1; }
	@test -r "$(ADR_INDEX_OUTRO)" || { printf '%s\n' 'Missing ADR landing-page conclusion' >&2; exit 1; }
	@tmp="$(ADR_INDEX_FILE).tmp"; \
	trap 'rm -f "$$tmp"' EXIT; \
	bash "$(ADRCTL)" generate toc -i "$(ADR_INDEX_INTRO)" -o "$(ADR_INDEX_OUTRO)" >"$$tmp"; \
	mv "$$tmp" "$(ADR_INDEX_FILE)"; \
	trap - EXIT

## Generate stable reference documentation with bashdeps-pinned released filters.
docs: deps-docs-check
	$(MAKE) --no-print-directory docs-canary \
		AWK_DOXYGEN_FILTER="$(VENDOR_AWK_FILTER)" \
		BASH_DOXYGEN_FILTER="$(VENDOR_BASH_FILTER)"

## Generate reference documentation with explicitly selected filter paths.
##
## This target is also the common integration-canary path. It does not acquire
## or repair dependencies; callers prepare stable documentation dependencies
## separately and may substitute current-source or exact-release Bash filter bytes.
docs-canary:
	@test -f "$(AWK_DOXYGEN_FILTER)" || { printf '%s\n' 'Missing AWK Doxygen filter' >&2; exit 1; }
	@test -f "$(BASH_DOXYGEN_FILTER)" || { printf '%s\n' 'Missing Bash Doxygen filter' >&2; exit 1; }
	chmod 0755 "$(AWK_DOXYGEN_FILTER)" "$(BASH_DOXYGEN_FILTER)"
	"$(AWK_BIN)" -f "$(AWK_DOXYGEN_FILTER)" -- --strict --compact "$(SOURCE_FILTER)" >/dev/null
	awk -f "$(BASH_DOXYGEN_FILTER)" -- --strict --compact ./tests/run-tests.sh >/dev/null
	$(MAKE) --no-print-directory adr-index
	$(MAKE) --no-print-directory docs-clean
	AWK_DOXYGEN_FILTER="$(abspath $(AWK_DOXYGEN_FILTER))" \
	BASH_DOXYGEN_FILTER="$(abspath $(BASH_DOXYGEN_FILTER))" \
		doxygen Doxyfile

## Remove generated reference documentation.
docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"

clean: docs-clean
	rm -rf "$(DIST_DIR)"

## Remove all generated build, reference, ADR-navigation, and dependency state.
distclean: clean
	rm -rf "$(VENDOR_DIR)"
	rm -f "$(ADR_INDEX_FILE)"

include mk/megalinter.mk
