# Canonical build, validation, and release-artifact entry points.

SHELL := /bin/sh
.SHELLFLAGS := -eu -c

DIST_DIR := dist
SOURCE_FILTER := doxygen-bash.awk
DIST_FILTER := $(DIST_DIR)/doxygen-bash.awk
DIST_CHECKSUM := $(DIST_FILTER).256

VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build checksums clean test test-source test-dist

all: build

## Build the exact consumer artifact with immutable provenance metadata.
##
## The build target is intentionally phony because VERSION, BUILD_DATE, and
## BUILD_COMMIT are build inputs rather than filesystem prerequisites. Rebuilding
## prevents development metadata from leaking into a later release artifact.
## The maintained awk source remains the source of truth; the generated artifact
## preserves its executable shebang and adds metadata only as comments so the
## filter's runtime behavior and awk namespace remain unchanged.
build: $(SOURCE_FILTER)
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/awk -f'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Source files: $(SOURCE_FILTER)'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# DOXYGEN_BASH_VERSION=$(VERSION)'; \
		printf '%s\n' '# DOXYGEN_BASH_BUILD_DATE=$(BUILD_DATE)'; \
		printf '%s\n' '# DOXYGEN_BASH_BUILD_COMMIT=$(BUILD_COMMIT)'; \
		printf '%s\n' '#'; \
		tail -n +2 "$(SOURCE_FILTER)"; \
	} >"$(DIST_FILTER).tmp"
	chmod 0755 "$(DIST_FILTER).tmp"
	mv "$(DIST_FILTER).tmp" "$(DIST_FILTER)"

## Run the regression suite against both maintained source and consumer output.
test: test-source test-dist

## Run the regression suite against the maintained source file.
test-source:
	DOXYGEN_BASH_FILTER="$(SOURCE_FILTER)" sh ./test/run-tests.sh

## Build and run the regression suite against the exact consumer artifact.
test-dist: build
	DOXYGEN_BASH_FILTER="$(DIST_FILTER)" sh ./test/run-tests.sh

## Generate the SHA-256 checksum for the exact consumer artifact.
##
## The checksum is generated from inside dist so users can download both files
## into one directory and verify them with sha256sum -c doxygen-bash.awk.256.
checksums: build
	cd "$(DIST_DIR)" && sha256sum "$(notdir $(DIST_FILTER))" >"$(notdir $(DIST_CHECKSUM))"

clean:
	rm -rf "$(DIST_DIR)"
