---
name: Tests

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    name: Test suite
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run test suite
        run: make test
